# Generated by Django 4.2.4 on 2023-08-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CustomerName", models.CharField(max_length=500)),
                ("CustomerPAN", models.CharField(max_length=10)),
                ("Organization", models.CharField(max_length=200)),
                ("UploadedDate", models.DateField()),
                ("Status", models.CharField(max_length=200)),
                ("UploadedDocuments", models.CharField(max_length=500)),
            ],
        ),
    ]
