# Generated by Django 4.2.4 on 2023-08-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainapp",
            name="Contact",
            field=models.IntegerField(null=True),
        ),
    ]
